### ISSUE TITLE
Hello!! 어떻게 먹고 살것인가.

### ISSUE THREAD

**Issue by youngjin-song** [youngjin-song/HelloWorld#1]
신난다. 

대박

@youngjin-song 
![KakaoTalk_20190903_125344910](https://user-images.githubusercontent.com/52528954/65130994-71474d00-da39-11e9-94c7-9c210dfd3b32.jpg)
#

**Comment by youngjin-song** [comment]
그냥 잘 살면 되지.

**Comment by Kerry-Cho** [comment]
머하십니까 형님 ㅋㅋ
